[package]
name = "dualcube"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
dualcube-dual = { path = "../dualcube-dual" }
dualcube-flow = { path = "../dualcube-flow" }
dualcube-primal = { path = "../dualcube-primal" }
dualcube-quad = { path = "../dualcube-quad" }
dualcube-types = { path = "../dualcube-types" }
grapff = { path = "../grapff" }
slotmap = "1.0.7"
rand = "0.10.1"

serde = { version = "1.0.188", features = ["rc"] }
thiserror = "2.0.17"
orx-parallel = "3.4.0"

[lints]
workspace = true
[dev-dependencies]
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
