[package]
name = "dualcube-types"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
name = "dualcube_types"

[dependencies]
mehsh = { path = "../mehsh", features = ["obj", "stl"] }
grapff = { path = "../grapff" }
serde = { version = "1.0.188", features = ["derive"] }
itertools = { version = "0.15.0" }
tracing = { version = "0.1.44", features = ["release_max_level_info"] }
ordered-float = "5.0.0"

[lints]
workspace = true