[package]
name = "dualcube-primal"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
name = "dualcube_primal"

[dependencies]
dualcube-dual = { path = "../dualcube-dual" }
dualcube-types = { path = "../dualcube-types" }
bimap = "0.6.3"
orx-parallel = "3.4.0"
rand = "0.10.1"
serde = { version = "1.0.188", features = ["rc", "derive"] }
thiserror = "2.0.17"

[lints]
workspace = true
