[package]
name = "cli"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
dualcube = { path = "../../crates/dualcube" }
io = { path = "../../crates/dualcube-io" }

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.20", features = ["fmt"] }
anyhow = "1.0"

[lints]
workspace = true
